.TH RUNOFF_FILENAMES 7
.SH NAME
runoff_filenames \- filename extensions for RUNOFF
.
.\" The .SH was moved to this place in order to appease `apropos'.
.
.\" --------------------------------------------------------------------
.\" Legalese
.\" --------------------------------------------------------------------
.
.de copying
Copyright 2014 Bernd Warken <bernd.warken@web.de>

Last update: 5 Jan 2014

This file is part of RUNOFF, a free software project.

You can redistribute it and/or modify it under the terms of the GNU
General Public License version 2 or (at your option) any later
version. as published by the Free Software Foundation (FSF).

You can find the text of this license in the file
.B gpl-2.0.txt
in this package, it's also available in the internet at
.UR http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
.UE .
..
.
.
.\" --------------------------------------------------------------------
.\" Setup
.\" --------------------------------------------------------------------
.
.ds1 Ellipsis "\&.\|.\|.\&"
.
.\" --------------------------------------------------------------------
.\" Macro definitions
.\" --------------------------------------------------------------------
.
.\" --------------------------------------------------------------------
.\" .FONT (<font name> <text> [<font name> <text> ...])
.\"
.\" Print in different fonts: R, I, B, CR, CI, CB
.\"
.de1 FONT
.  if (\\n[.$] = 0) \{\
.	nop \&\f[]\&
.	return
.  \}
.  ds result \&
.  while (\\n[.$] >= 2) \{\
.	as result \,\f[\\$1]\\$2\f[]
.	shift 2
.  \}
.  if (\\n[.$] = 1) .as result \,\f[\\$1]
.  nh
.  nop \\*[result]\&
.  hy
..
.
.\" --------------------------------------------------------------------
.\" End of macro definitions
.\" --------------------------------------------------------------------
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
Since the evolution of
.FONT CI RUNOFF
in the 1960s, a whole bunch of filename extensions for
.FONT CI RUNOFF
files were used.
.
.
.\" --------------------------------------------------------------------
.SH HISTORICAL RUNOFF LANGUAGES
.\" --------------------------------------------------------------------
.
The first text language that used the
.FONT CB .COMMAND
structure for defining commands is said to be the
.FONT CI MEMO
language with programs
.FONT CB MODIFY
and
.FONT CB DITTO R .
.
It was used at
.FONT CR MIT
under the operating system
.FONT CR CTSS
in the years 1960\-63.
.
But there is no open documentation for this old text system, but it
seems that there is 1 book about it in the non-public library at
.FONT CB MIT R .
.
.
.P
The letter
.FONT CB m
taken from
.FONT CI MEMO R / MODIFY
is still active as the option
.FONT CB -m
for declaring a macro package in
.FONT CB troff R / CB nroff R .
.
.
.P
The first documented
.FONT CB .COMMAND
text language was
.FONT CI RUNOFF R ,
see
.BR runoff (@MAN7EXT@).
.
.
.\" --------------------------------------------------------------------
.SS RUNOFF Files
.\" --------------------------------------------------------------------
.
All available
.FONT CI RUNOFF
files are now kept in the internet at an archive on
.FONT CI github R .
.
Use the command-line call
.RS
.EX
.FONT CR "$ " CB "git clone git@github.com:RUNOFF/RUNOFF.git"
.EE
.RE
for getting this archive (without the leading dollar).
.
.
.TP
.FONT I <name> CB .RUNOFF
.TQ
.FONT I <name> CB .runoff
were the oldest naming for files in the original
.FONT CI RUNOFF
format of the 1960s at
.FONT CR "IBM 7090"
and
.FONT CR 7094
with the operating system
.FONT CR CTSS R .
.
.
.TP
.FONT I <name> CB .RUN
.TQ
.FONT I <name> CB .run
This abbreviation was used for
.FONT CI RUNOFF
files on the
.FONT CR CTSS
and
.FONT CR Multics
operating system in the 1960s and later on.
.
.
.TP
.FONT I <name> CB .RNO
.TQ
.FONT I <name> CB .rno
was used for normal
.FONT CI RUNOFF
text files, mostly on the
.FONT CR "PDP10\-10 archive" R .
.
.
.TP
.FONT I <name> CB .RNH
.TQ
.FONT I <name> CB .rnh
was used for help files written in the
.FONT CI RUNOFF
language on the
.FONT CR "PDP10\-10 archive" R .
.
.
.P
.FONT CI RUNOFF
files with the extensions
.FONT CB .rnh R ,
.FONT CB .rno R ,
and
.FONT CB .run
are still available in the internet at several sites, mostly at the
.FONT CR "DEC PDP\-10 archive" R .
.
See
.nh
.UR http://\:pdp\-10.trailing\-edge.com/\:cgi-bin/\:searchbyname?name=*.rnh
RNH
.UE ,
.UR http://\:pdp\-10.trailing\-edge.com/\:cgi-bin/\:searchbyname?name=*.rno
RNO
.UE ,
and
.UR http://\:pdp\-10.trailing\-edge.com/\:cgi-bin/\:searchbyname?name=*.run
RUN
.UE  .
.hy
.
.
.\" --------------------------------------------------------------------
.SS Processed RUNOFF Text Files
.\" --------------------------------------------------------------------
.
Files written in the
.FONT CI RUNOFF
language were processed by the program
.FONT CB RUNOFF R .
.
Only text files were produced by this step, because graphics was not
available in the 1960s.
.
Today we would use the file name extension
.FONT CI * CB .txt R .
.
That was not done in these early times.
.
Instead the following extensions were taken:
.
.
.TP
.FONT I <name> CB .DOC
.TQ
.FONT I <name> CB .doc
Very often this naming was used for the output of the
.FONT CB RUNOFF
program.
.
It contained
.I filled
and
.I hyphenated
text, suitable for tty mode.
.
The extension
.FONT CB .doc
was later on taken by
.FONT CR Microsoft
for their
.IR "office files" .
.
.
.TP
.FONT I <name> CB .MEM
.TP
.FONT I <name> CB .mem
This often used extension was taken for
.FONT CI RUNOFF
files to refer to the ancient
.FONT CI MEMO
language.
.
.
.TP
.FONT I <name> CB .HLP
.TQ
.FONT I <name> CB .hlp
The formatting of
.FONT CI * CB .rnh
files (help files) was stored under this extension.
.
.
.P
This ends the description of
.FONT CI RUNOFF .R .
.
All following parts of this document refer to the
.FONT CI roff
language and the used file name extensions thereof.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR runoff2mom (1),
.BR runoff (7),
.BR runoff_history (7)
.
.
.P
If you need ancient files written in the
.I RUNOFF
language or documentation of old time, have a look at
.RS
.EX
git clone https://github.com/RUNOFF/RUNOFF
.EE
.RE
.
.
.\" --------------------------------------------------------------------
.SH "LICENSE"
.\" --------------------------------------------------------------------
.
.copying
.
.
.\" --------------------------------------------------------------------
.\" Emacs settings
.\" --------------------------------------------------------------------
.
.\" Local Variables:
.\" mode: nroff
.\" End:
